---
title: "MIRT for Sam"
author: "Luis Sandoval-Araujo"
date: "2024-02-15"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
rm(list = ls())
library(mirt)
library(tidyverse)
library(haven)
```

```{r}
#looks like sam preferred mirt
setwd("C:/Users/Luis/Dropbox/independent stuff/Year 1/Sam MIRT") #make my life easier
CIA = read_sav('Mturk_CIA_DemoCIA-only.sav')
#CIA = read.csv("Mturk_sexatbirthCIA_M1F2_noNAcases.csv") #old file plz ignore
```


```{r, eval=FALSE}
head(CIA)#looking at data real quick
colnames(CIA)#seeing all the columns we need
```


```{r}
CIA = CIA[complete.cases(CIA[,58:73]),] #removing cases where CIA answers were not provided
count(CIA) #4 removed for NA - correct
```
```{r}
SAB = subset(CIA, (SAB == 1 | SAB == 2)) #only participants that answered SAB with 1 or 2 - final n = 1733
```

```{r}
#making a variable for GenderIdentity, 1 = not cisgender, 0 = cis, NA = notsure/PNTA
xtabs(~NotSure + PNTA_gender, SAB) #there are 1508 cases that are not notsure/PNTA
SAB$NotCis = ifelse(SAB$PNTA_gender == 1, NA, ifelse(
  SAB$TransMasc == 1 | SAB$TransFem == 1 | SAB$Genderqueer == 1 | SAB$Expansive == 1 | 
    SAB$Agender == 1 | SAB$Andro == 1 | SAB$NonBinary == 1 | SAB$TwoSpirited == 1, 
  1, 
  ifelse(
    SAB$CisMan == 1 | SAB$CisWoman == 1, 
    0, NA)))
SAB$NotCis = as.factor(SAB$NotCis)
levels(SAB$NotCis) = list("cis"=0, "not cis"=1)
table(SAB$NotCis) 
#565 identify as not cis, 923 cis
#565 + 923 = 1488 - there's 4 additional participants here. participants were excluded if they put PNTA, regardless of if they endorsed something else. if participants only put 'not sure', they were excluded, but were included if they endorsed any other characteristic aside from cis



#variable for Sexuality, 1 = not hetero, 0 = hetero
table(SAB$PNTA_sexorientation) #62 participants PNTA sexual orientation
SAB$NotHet = ifelse(
  SAB$PNTA_sexorientation == 1,
  NA,
  ifelse(
    SAB$Asexual == 1 | SAB$Bisexual == 1 | SAB$Gay == 1 | SAB$Lesbian == 1 | SAB$Pansexual == 1 | SAB$Queer == 1 | SAB$Questioning == 1 | SAB$Gray == 1 | SAB$Demisexual == 1 | SAB$SameGenderLoving == 1, 1, 
    ifelse(SAB$Hetero == 1, 0, NA)))

SAB$NotHet = as.factor(SAB$NotHet)
levels(SAB$NotHet) = list("het"=0, "not het"=1)
table(SAB$NotHet) 
#771 identify as not hetero, 894 het
#1733 - 62 = 1671
#771 + 894 = 1665, 6 missing



#coding sexual and gender minorities - cishet = 0, SGM = 1
SAB$SGM = ifelse(SAB$NotCis == "not cis" | SAB$NotHet == "not het", 1, 0)
table(SAB$SGM) #759 non-SGM, 825 SGM, total = 1584
SAB$SGM = as.factor(SAB$SGM)
levels(SAB$SGM) = list("cishet"=0, "SGM"=1)




#coding AFAB vs. AMAB SGM, 1 = AMAB SGM, 2 = AFAB SGM
xtabs(~SAB$SGM + SAB$SAB) #there are 335 AMAB SGM and 490 AFAB SGM
SAB$SAB_SGM = ifelse(SAB$SGM == "SGM" & SAB$SAB == 1, 1, ifelse(SAB$SGM == "SGM" & SAB$SAB == 2, 2, NA))
table(SAB$SAB_SGM) #yeah that lines up
SAB$SAB_SGM = as.factor(SAB$SAB_SGM)




#coding AFAB SGM vs. AFAB cishet, Hetero = 1, SGM = 2
#gonna start by making an AFAB variable
SAB$AFAB = ifelse(SAB$SAB == 2, 1, 0) #1026 AFAB, 1 = AFAB, 0 = Not AFAB
xtabs(~SAB$SGM + SAB$AFAB) #there are 490 AFAB SGM, 444 AFAB cishet, that's 934... where are the rest
SAB$AFAB_SGM = ifelse(SAB$AFAB == 1 & SAB$SGM == "SGM", 2, ifelse(SAB$AFAB == 1 & SAB$SGM == "cishet", 1, NA))




#coding AMAB SGM vs. AMAB hetero
SAB$AMAB = ifelse(SAB$SAB == 1, 1, 0) #707 AMAB
xtabs(~SAB$SGM + SAB$AMAB) #there are 315 cishet AMAB and 335 SGM AMAB. that's 650 participants 
SAB$AMAB_SGM = ifelse(SAB$AMAB == 1 & SAB$SGM == "SGM", 2, ifelse(SAB$AMAB == 1 & SAB$SGM == "cishet", 1, NA)) #woo we got it right
```


```{r}
# clinical impairment scale(CIA; Bohn et al., 2008; Bohn & Fairburn, 2008; Kambanis MTurk Dataset)

CIA_SAB = subset(SAB, (SAB == 1 | SAB == 2), select = c(CIA1:CIA16, SAB))
CIA_SAB = na.omit(CIA_SAB)
range(CIA_SAB) #items range from 0-3
head(CIA_SAB) 
```

```{r}
cluster = mirtCluster()
```

```{r}
#F1 = Personal impairment 
#F2 = Social impairment 
#F3 = Cognitive impairment
fstruct3 = 'F1 = CIA2,CIA8,CIA9,CIA11,CIA14,CIA16
F2 = CIA3,CIA7,CIA10,CIA12,CIA15
F3 = CIA1,CIA4,CIA5,CIA6,CIA13' 
``` 

```{r}
#mirt model on SAB
mod1 <-mirt(CIA_SAB[,1:16], fstruct3)
coef(mod1)
summary(mod1, suppress = .25) 
```

```{r}
CIA_SAB$SAB2<-ifelse(CIA_SAB$SAB==2, "F","M") #categorical variable
CIA_SAB$SAB2 = as.factor(CIA_SAB$SAB2)

#it looks like we need mirt.model() somewhere here
```


```{r}
fstruct6 = mirt.model('F1=2,8,9,11,14,16
                      F2=3,7,10,12,15
                      F3=1,4,5,6,13
                      COV = F1*F2*F3') #adding covariate to the model syntax

multimod3 = multipleGroup(CIA_SAB[,1:16],
                         model = fstruct6, 
                         itemtype = 'graded', 
                         group = CIA_SAB$SAB2, 
                         invariance = c("CIA1", "CIA7", "CIA10",
                                        "CIA12","CIA16", "free_means", "free_var"),
                         method = 'QMCEM', 
                         SE = TRUE, 
                         mirtCluster = cluster) #SE.type = "sandwich") 
#literally just trying it again; items 1, 7, 10, 12, and 16 were identified as anchors based on unidimensional dif using lordif() according to sam
#sam picked a seed of 15
#default EM method will not run after 26 iterations
summary(multimod3)
```

```{r}
dif3 <-DIF(multimod3, c('a1', 'a2', 'd1', 'd2', 'd3'),
          p.adjust = 'BH', 
          items2test=c(2:6,8:9,11,13:15), 
          seq_stat= .01,
          method = 'QMCEM') 
dif3
```

```{r}
itemfit(multimod3, S_X2.plot = 2)
```

```{r}
CIA_SGM = CIA
CIA_SGM$SGM_num = as.numeric(CIA_SGM$SGM)
CIA_SGM$SGM_num = ifelse(CIA_SGM$SGM_num == 1, 0, 1)
CIA_SGM = subset(CIA_SGM, SGM_num == 1 | SGM_num == 0)

write.csv(CIA_SGM, "CIA_SGM.csv")
```

```{r}
#let's start looking at AFAB vs AMAB SGM
CIA_SABbySGM = subset(CIA, SAB_SGM >= 1, select = c(CIA1:CIA16, SAB_SGM))
CIA_SABbySGM$SAB_SGM = as.factor(CIA_SABbySGM$SAB_SGM)
levels(CIA_SABbySGM$SAB_SGM) = list("AMAB_SGM"=1, "AFAB_SGM"=2) #1 = AMAB SGM, 2 = AFAB SGM


SABbySGM = multipleGroup(CIA_SABbySGM[,1:16],
                         model = fstruct6, 
                         itemtype = 'graded', 
                         group = CIA_SABbySGM$SAB_SGM, 
                         invariance = c("CIA1", "CIA7", "CIA10",
                                        "CIA12","CIA16", "free_means", "free_var"),
                         method = 'QMCEM', 
                         SE = TRUE, 
                         mirtCluster = cluster)
```

```{r}
dif_sab_sgm <-DIF(SABbySGM, c('a1', 'a2', 'd1', 'd2', 'd3'),
          p.adjust = 'BH', 
          items2test=c(2:6,8:9,11,13:15), 
          seq_stat= .01,
          method = 'QMCEM') 

dif_sab_sgm
```

```{r}
library (ltm)
library(lordif)

#running lordif to find anchors for cishet vs sgm comparison
#thanks sam for the... code, i guess
CIA_SGM_subset <- subset(CIA_SGM,(SGM_num==0 |SGM_num==1), select = c(CIA1:CIA16, SGM))
CIA_SGM_subset <-na.omit(CIA_SGM_subset) 

#Fit constrained GRM
mod1 <-grm(CIA_SGM_subset[,1:16], constrained= TRUE)
mod1
#Dscrmn = discrimination parameter (constrained set to true, so constant)
#Extrmt = extremity parameters; 1 = CIA "ability level" at 50% chance selecting option 1; 
# 2 = ability level of CIA at 50% chance of selecting option 1 or2; 3, options 1,2,3, etc.

#Fit non-constrained GRM
#Dscrmn now different across different items
mod2 <- grm(CIA_SGM_subset[,1:16])
mod2

#Compare fit of constrained versus non-constrained GRM with 
#likelihood ratio test 
#if significant ANOVA - non-constrained model (model 2) showed improvement in fit 
anova(mod1,mod2)

#Plot Item Response Characteristic Curve (IRCC)
plot(mod2)

#Plot Test Information Function (TIF)
#when you set items to zero, gives entire TIF, but can also 
#set items equal to the one(s) you want to look at
plot(mod2, type="IIC", items=0)

#Plot Item Information Function (IIF) for each item
plot(mod2, type="IIC")

#Estimates of Clinical Impairment (i.e., theta) by participant
#Expected range (-3 <= theta <= 3)
est <-factor.scores(mod2)

#show first ten participants only
#look at negative values - see # participants pulling at lower level of 'ability' on CIA
est$score.dat$z1[1:16]

CIA_SGM_subset$SGM = as.numeric(CIA_SGM_subset$SGM)
cvntDIF <-lordif(as.data.frame(CIA_SGM_subset[,1:16]), group = CIA_SGM_subset$SGM, criterion = 'Chisqr', alpha = 0.01)
cvntDIF

###################
#FOR INTERPRETATION
###################
#ncat refers to number of categories for each item (CIA items 0-3; 4 ncat)
#three nested OLR models & chisq test compares each pair of three tests;
#first column compares model 1 and model 2 - tries to detect uniform DIF
#second looks at both uniform & non-uniform DIF
#third column tries to detect just non-uniform

#uniform DIF = constant across levels of ability 
#non-uniform = differs across levels of ability 
#Flagged as DIF item if ONE of the above tests is significant 
#############################################################################

plot(cvntDIF, labels = c('cishet', 'shestheysgays'))
```


```{r}
#tabling this for now 
#running for bias between sex at birth for cishet people
CIA_CIS = CIA
CIA_CIS$CisMan = as.numeric(CIA_CIS$CisMan)
CIA_CIS$CisWoman = as.numeric(CIA_CIS$CisWoman)
CIA_CIS$Hetero = as.numeric(CIA_CIS$Hetero)
CIA_CIS$isCishet = ifelse(CIA_CIS$CisMan == 1 | CIA_CIS$CisWoman == 1 & CIA_CIS$Hetero == 1, 1, 0)
CIA_CIS = subset(CIA_CIS, isCishet == 1) #idk why this kept cases where Hetero = 0
CIA_CIS = subset(CIA_CIS, Hetero == 1) #this fixes it but there are 4 cases where CisMan == 1 and CisWoman == 1, so need to drop them somehow
CIA_CIS$doublecalc = CIA_CIS$CisMan + CIA_CIS$CisWoman #calculating if these two variables combined == 2, we know they endorsed both
CIA_CIS$isCishet = ifelse(CIA_CIS$doublecalc == 2, NA, CIA_CIS$isCishet) #turning cases where both CisMan and CisWoman are endorsed into NAs
CIA_CIS = CIA_CIS[!is.na(CIA_CIS$isCishet),] #yay we got rid of them

CIA_CIS$SAB = as.factor(CIA_CIS$SAB)
#subsetting to keep just CIA items and SAB
CIA_CIS = subset(CIA_CIS, CIA_CIS$isCishet == 1, select = c(CIA1:CIA16, SAB))

#we don't need another variable for assigned sex at birth by cishet status i think - it's assumed that sex assignment at birth is congruent with their gender identity, so this is basically the same model as the F vs. M one except 
CisHet = multipleGroup(CIA_CIS[,1:16],
                         model = fstruct6, 
                         itemtype = 'graded', 
                         group = CIA_CIS$SAB, 
                         invariance = c("CIA1", "CIA7", "CIA10",
                                        "CIA12","CIA16", "free_means", "free_var"),
                         method = 'QMCEM', 
                         SE = TRUE,
                       TOL = .00001,
                       mirtCluster = cluster)
```

```{r}
dif_cishet <-DIF(CisHet, c('a1', 'a2', 'd1', 'd2', 'd3'),
          p.adjust = 'BH', 
          items2test=c(2:6,8:9,11,13:15), 
          seq_stat= .01,
          method = 'QMCEM') 
```

